apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api-image:latest  # Change name image
        ports:
        - containerPort: 5000  
        envFrom:
        - configMapRef:
            name: app-config  
        - secretRef:
            name: app-secret  